struct SubSpace: BaseThemePage {
    var themedContent: String {
        """
        A subspace is a vector space that is entirely contained within another vector space

        A Subspace Spanned by a Set

        If v1 ... vp are in vector space V, then Span{v1, ..., vp} is a subspace of V.

        We call Span{v1, ..., vp} the subspace spanned or generated by {v1, ..., vp} Given any subspace H of V, a spanning or generating set for H is a set {v1, ..., vp} in h such that H = Span{v1, ..., vp}.

        Given a set of Vectors. There general solution of parametric vector form is a the set of vectors that Span H

        """
    }
    var related: [any BaseThemePage.Type] = [
        Image.self,
        NullSpace.self,
        ColumnSpace.self,
        RowSpace.self,
        LinearTransformation.self,
        Span.self,
        VectorSpace.self,
    ]
}
