struct VectorEquation: MathWebPage {
    var markupDescription: String {
        """
        TODO add latex for vector equation
        TODO add this as a function so that I can call it to create latex
        vector equations in other descriptions or structures


        A vector equation is a sum of vectors parried with scalar multiplies that add up to the solution b. This is often phased and b can be generated by a linear combination of the vectors in the vector equation. This must still respects the rules of math ie 0 != 1
        """
    }
}
